package Java8.StreamsApi.StreamCreation.InfiniteStream;

import java.util.stream.Stream;

public class StreamGenerate {
  public static void main(String[] args) {
    //The generate() method of the Stream interface returns an infinite sequential unordered stream where each element is generated by the provided Supplier.
    // Note: There is no fixed size for the stream. We can limit the number of elements by using the limit() method. If we don't use the limit() method, it will generate an infinite stream.
    //Create a stream of random numbers
    //Care should be taken while using the generate() method because it can generate an infinite stream.
    Stream.generate(() -> Math.random()).limit(5).forEach(System.out::println);//

    //create a stream of random integers
    Stream.generate(() -> (int) (Math.random() * 100)).limit(5).forEach(System.out::println);//Random integers

    //Create a stream of 5
    Stream.generate(() -> 5).limit(5).forEach(System.out::println);//5 5 5 5 5

  }
}
